// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title IERC20
 * @dev Minimal BEP-20 / ERC-20 interface required for token distribution.
 */
interface IERC20 {
    function totalSupply() external view returns (uint256);
    function balanceOf(address account) external view returns (uint256);
    function transfer(address recipient, uint256 amount) external returns (bool);
    function allowance(address owner, address spender) external view returns (uint256);
    function approve(address spender, uint256 amount) external returns (bool);
    function transferFrom(address sender, address recipient, uint256 amount) external returns (bool);

    event Transfer(address indexed from, address indexed to, uint256 value);
    event Approval(address indexed owner, address indexed spender, uint256 value);
}

/**
 * @title PepeClaimDistributor
 * @notice Real Web3 Airdrop / Referral Token Claim Distributor for PEPE BEP-20 tokens.
 * Users claim tokens directly to their BEP-20 wallet (e.g. MetaMask / Trust Wallet)
 * by verifying a cryptographic signature voucher issued by the authorized backend server.
 */
contract PepeClaimDistributor {
    // Contract owner
    address public owner;

    // Authorized backend signer address that cryptographically approves claims
    address public signer;

    // BEP-20 PEPE token contract address
    address public immutable token;

    // Emergency pause state
    bool public paused;

    // Reentrancy guard state
    uint256 private _status;
    uint256 private constant _NOT_ENTERED = 1;
    uint256 private constant _ENTERED = 2;

    // Total statistics
    uint256 public totalClaimed;
    uint256 public totalClaimsCount;

    // Mapping to track used claim nonces to prevent replay attacks
    mapping(uint256 => bool) public isClaimed;

    // Events
    event TokensClaimed(
        address indexed recipient,
        uint256 amount,
        uint256 indexed nonce,
        uint256 timestamp
    );
    event SignerUpdated(address indexed previousSigner, address indexed newSigner);
    event OwnershipTransferred(address indexed previousOwner, address indexed newOwner);
    event TokensDeposited(address indexed from, uint256 amount);
    event EmergencyWithdrawal(address indexed token, address indexed to, uint256 amount);
    event Paused();
    event Unpaused();

    modifier onlyOwner() {
        require(msg.sender == owner, "Only contract owner can call this");
        _;
    }

    modifier whenNotPaused() {
        require(!paused, "Claims are currently paused");
        _;
    }

    modifier nonReentrant() {
        require(_status != _ENTERED, "ReentrancyGuard: reentrant call");
        _status = _ENTERED;
        _;
        _status = _NOT_ENTERED;
    }

    /**
     * @param _token The BEP-20 token address (e.g. PEPE token contract)
     * @param _signer The public address corresponding to the backend's private key
     */
    constructor(address _token, address _signer) {
        require(_token != address(0), "Invalid token address");
        require(_signer != address(0), "Invalid signer address");

        owner = msg.sender;
        signer = _signer;
        token = _token;
        _status = _NOT_ENTERED;
        paused = false;

        emit OwnershipTransferred(address(0), msg.sender);
        emit SignerUpdated(address(0), _signer);
    }

    /**
     * @notice Claim PEPE tokens via cryptographically signed voucher from the DApp backend.
     * @param amount The raw token amount to claim (including token decimals)
     * @param nonce A unique redemption identifier generated by the backend
     * @param deadline Expiration timestamp (seconds since Unix epoch)
     * @param signature The 65-byte ECDSA signature signed by the backend signer
     */
    function claim(
        uint256 amount,
        uint256 nonce,
        uint256 deadline,
        bytes calldata signature
    ) external whenNotPaused nonReentrant {
        require(amount > 0, "Claim amount must be greater than zero");
        require(block.timestamp <= deadline, "Voucher signature has expired");
        require(!isClaimed[nonce], "Voucher has already been claimed");

        // Hash parameters: recipient (msg.sender), amount, nonce, deadline, and this contract address
        bytes32 messageHash = keccak256(
            abi.encodePacked(msg.sender, amount, nonce, deadline, address(this))
        );

        // Convert to Ethereum Signed Message format (RFC 191)
        bytes32 ethSignedHash = keccak256(
            abi.encodePacked("\x19Ethereum Signed Message:\n32", messageHash)
        );

        // Recover signer from signature
        address recoveredSigner = recoverSigner(ethSignedHash, signature);
        require(
            recoveredSigner != address(0) && recoveredSigner == signer,
            "Invalid voucher cryptographic signature"
        );

        // Mark nonce as claimed immediately (prevent replay)
        isClaimed[nonce] = true;
        totalClaimed += amount;
        totalClaimsCount++;

        // Verify contract token balance
        uint256 contractBalance = IERC20(token).balanceOf(address(this));
        require(contractBalance >= amount, "Distributor has insufficient PEPE tokens. Contact admin.");

        // Transfer tokens to recipient
        bool success = IERC20(token).transfer(msg.sender, amount);
        require(success, "Token transfer failed");

        emit TokensClaimed(msg.sender, amount, nonce, block.timestamp);
    }

    /**
     * @notice Verify whether a given nonce has already been claimed
     */
    function isNonceClaimed(uint256 nonce) external view returns (bool) {
        return isClaimed[nonce];
    }

    /**
     * @notice Get current token balance held by this distributor contract
     */
    function getContractTokenBalance() external view returns (uint256) {
        return IERC20(token).balanceOf(address(this));
    }

    /**
     * @notice Deposit tokens into distributor contract (requires approve() first)
     */
    function depositTokens(uint256 amount) external {
        require(amount > 0, "Deposit amount must be > 0");
        bool success = IERC20(token).transferFrom(msg.sender, address(this), amount);
        require(success, "Deposit transfer failed");
        emit TokensDeposited(msg.sender, amount);
    }

    /**
     * @notice Update backend authorized signer address
     */
    function setSigner(address _newSigner) external onlyOwner {
        require(_newSigner != address(0), "Invalid signer address");
        emit SignerUpdated(signer, _newSigner);
        signer = _newSigner;
    }

    /**
     * @notice Transfer contract ownership
     */
    function transferOwnership(address _newOwner) external onlyOwner {
        require(_newOwner != address(0), "Invalid new owner");
        emit OwnershipTransferred(owner, _newOwner);
        owner = _newOwner;
    }

    /**
     * @notice Pause claims in emergency
     */
    function pause() external onlyOwner {
        paused = true;
        emit Paused();
    }

    /**
     * @notice Resume claims
     */
    function unpause() external onlyOwner {
        paused = false;
        emit Unpaused();
    }

    /**
     * @notice Emergency withdrawal of tokens by owner
     */
    function emergencyWithdraw(address _tokenAddress, uint256 amount) external onlyOwner {
        require(_tokenAddress != address(0), "Invalid token address");
        require(amount > 0, "Amount must be > 0");
        bool success = IERC20(_tokenAddress).transfer(owner, amount);
        require(success, "Emergency withdraw transfer failed");
        emit EmergencyWithdrawal(_tokenAddress, owner, amount);
    }

    /**
     * @dev Helper to recover address from ECDSA signature
     */
    function recoverSigner(bytes32 _ethSignedHash, bytes memory _sig) internal pure returns (address) {
        if (_sig.length != 65) {
            return address(0);
        }

        bytes32 r;
        bytes32 s;
        uint8 v;

        assembly {
            r := mload(add(_sig, 32))
            s := mload(add(_sig, 64))
            v := byte(0, mload(add(_sig, 96)))
        }

        if (v < 27) {
            v += 27;
        }

        if (v != 27 && v != 28) {
            return address(0);
        }

        return ecrecover(_ethSignedHash, v, r, s);
    }
}
